name: firebase_chat
description: "Flutter Firebase Chat App Case Study"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  emoji_picker_flutter: ^3.1.0
  firebase_messaging: ^15.1.6
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  flutter_notification_channel: ^3.1.0
  gallery_saver_plus: ^3.2.1
  lottie: ^3.2.0
  intl: ^0.20.1
  animate_do: ^3.3.4
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.3
  supabase: ^2.6.2
  shared_preferences: ^2.5.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/


