// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ei6yKObg6hfpxHCzNK4Pv2jxNPzEYN4',
    appId: '1:799537226231:android:239f46076a4a3d75624ef2',
    messagingSenderId: '799537226231',
    projectId: 'flutter-chatt-app-bb371',
    storageBucket: 'flutter-chatt-app-bb371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjxack2Uqg1RdbopYavmfbJsZ2o7swf1g',
    appId: '1:799537226231:ios:b799a194bdc7d728624ef2',
    messagingSenderId: '799537226231',
    projectId: 'flutter-chatt-app-bb371',
    storageBucket: 'flutter-chatt-app-bb371.firebasestorage.app',
    androidClientId: '799537226231-trhrjttf8phce07b4q7t5kesuk8i24ve.apps.googleusercontent.com',
    iosClientId: '799537226231-6lajthjhgsf4jjfdbrib1vt7rvcfqurh.apps.googleusercontent.com',
    iosBundleId: 'com.furky.chat',
  );

}